### PR TITLE
:bug: remove kcrypt hook after reset

### LINKED ISSUE #733: :bug: Reset fails when encryption is enabled
**Kairos version:**
[maser build](https://github.com/kairos-io/kairos/commit/2ada227c63ad1501173469ed52bb540c54fa64dc)

**CPU architecture, OS, and Version:**

**Describe the bug**
When trying to reset the machine, elemental can't find anymore `COS_PERSISTENT` (as it is encrypted), so the reset process skips deleting the `COS_PERSISTENT` partition

**To Reproduce**
Enable encryption, try to reset the machine

**Expected behavior**
The `COS_PERSISTENT` partition should be removed and recreated as usual. the `kcrypt` hook kicks in afterward to encrypt the partition with the passphrase.

**Logs**
VirtualBox_test-encryption_26_01_2023_09_47_53

### PR DESCRIPTION
**Pull request by paynejacob**
**What this PR does / why we need it**:

With the changes to elemental the elemental cli can now clear content from encrypted partitions.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #733

### CODE REVIEW

File: internal/agent/hooks/hook.go [hunk 1]
```diff
@@ -17,9 +17,7 @@ var AfterInstall = []Interface{
 	&Lifecycle{}, // Handles poweroff/reboot by config options
 }
 
-var AfterReset = []Interface{
```
Comment (mudler) [inline internal/agent/hooks/hook.go:20]: so I assume we don't re-encrypt anymore? Isn't elemental-cli deleting and recreating them?

Comment (Itxaka) [reply internal/agent/hooks/hook.go:20]: I have no idea how this works but cli is finding it, and formatting it, but only the mapped device (so /dev/mapper/sda5 for example) which means that the encryption is still in place no? Its only formatting the decrypted device, while the encrypted one hasnt changed.

Again, no idea, but its like erasing the contents of it only.

Comment (mudler) [reply internal/agent/hooks/hook.go:20]: Yup that sounds good then 👍

**Review by mudler — APPROVED** [review]
