### PR TITLE
:bug: Fix manual install not supporting configuration url

### LINKED ISSUE #764: kairos-agent does not work with a URL
**Kairos version:**
(there might be some typos here; the vmware remote console doesn't let me copy text, so I had to type this manually)
```
NAME="kairos-ubuntu-22-lts"
VERSION="v1.5.1-k3sv1.26.1+k3s1"
ID="kairos"
ID_LIKE="Kairos-ubuntu-22-lts"
VERSION_ID="v1.5.1-k3sv1.26.1+k3s1"
PRETTY_NAME="kairos-ubuntu-22-lts v1.5.1-k3sv1.26.1+k3s1"
ANSI_COLOR="0;32"
BUG_REPORT_URL="https://github.com/kairos-io/kairos/issues/new/choose"
HOME_URL="https://github.com/kairos-io/provider-kairos"
IMAGE_REPO="quay.io/kairos/kairos-ubuntu-22-lts"
IMAGE_LABEL="latest"
GITHUB_REPO="kairos-io/provider-kairos"
VARIANT="core"
FLAVOR="opensuse-leap"
```

**CPU architecture, OS, and Version:**
```
Linux localhost.localdomain 5.15.0-58-generic #64-Ubuntu SMP Thu Jan 5 11:43:13 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

**Describe the bug**
The program exists and outputs:
```
open http://10.10.0.20:9000/config.yml: no such file or directory
```

**To Reproduce**
1) On a server that the installer can talk to, write a config file and then host it with `python3 -m http.server 9000`
2) On the machine with the installer, run `sudo kairos-agent manual-install --reboot --device "auto" http://[ip addr of other machine]:9000/config.yml`

**Expected behavior**
As the help indicates, the installer will grab the config from the URL, and install it.

### PR DESCRIPTION
**Pull request by paynejacob**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #764

### CODE REVIEW

File: internal/agent/install.go [hunk 1]
```diff
@@ -63,28 +63,34 @@ func displayInfo(agentConfig *Config) {
 }
 
 func ManualInstall(c string, options map[string]string, strictValidations bool) error {
-	dat, err := os.ReadFile(c)
-	if err != nil {
-		return err
-	}
+	if _, err := url.Parse(c); err == nil {
```
Comment (mudler) [inline internal/agent/install.go:66]: This looks good, however can we isolate that in a function and have it covered by tests?

**Review by mudler — APPROVED** [review]
Looking good!

**Review by mudler — APPROVED** [review]
