### PR TITLE
:bug: Setup / as shared mount on alpine

### LINKED ISSUE #440: `/var/lib/longhorn` is not shared mounted
**Kairos version:**
1.1.7-alpine

**CPU architecture, OS, and Version:**

**Describe the bug**
Alpine can't be installed as `/var/lib/longhorn` seems to not be shared mounted

**To Reproduce**

**Expected behavior**

**Logs**
```
Warning  Failed          2m4s                kubelet            Error: failed to generate container "8424cf1a165ad1928a20fff7f65e863896018aedb1d8cbf47437b7dd8e7b6cee" spec: failed to generate spec: path "/var/lib/longhorn/" is mounted on "/var/lib/longhorn" but it is not a shared mount
```

**Additional context**

### PR DESCRIPTION
**Pull request by mudler**
Since this is not handled in the boot process, we do this in our devoted file to setup the rootfs configuration. It also adds an e2e test to verify that the mounts are correctly set

Signed-off-by: Ettore Di Giacinto <mudler@kairos.io>

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #440 

Thanks @christianprim for the finding!

### CODE REVIEW

File: tests/autoinstall_test.go [hunk 1]
```diff
@@ -156,6 +156,12 @@ var _ = Describe("kairos autoinstall test", Label("autoinstall-test"), func() {
 			Expect(out).To(ContainSubstring("/var/lib/longhorn"))
 		})
 
+		It("has rootfs shared mount", func() {
+			out, err := Sudo(`cat /proc/1/mountinfo | grep " / / "`)
+			Expect(err).ToNot(HaveOccurred())
```
Comment (jimmykarily) [inline tests/autoinstall_test.go:161]:
```suggestion
			Expect(err).ToNot(HaveOccurred(), out)
```
in case things break, this will provide more info

**Review by jimmykarily — DISMISSED** [review]

File: tests/autoinstall_test.go (hunk 1 above)
Comment (mudler) [reply tests/autoinstall_test.go]: good catch! thanks!

**Review by jimmykarily — DISMISSED** [review]

**Comment by christianprim** [comment]
Considering the output of "qemu-acceptance-tests (alpine) ", the command "mount --make-rshared /sysroot" failed in the fs stage. I wonder why not use "mount --make-rshared /" when root-partition is under /. Since the command recursively changes the type of all mounts, this should do the trick. Could be the last command before starting k3s...

**Comment by mudler** [comment]
> Considering the output of "qemu-acceptance-tests (alpine) ", the command "mount --make-rshared /sysroot" failed in the fs stage. I wonder why not use "mount --make-rshared /" when root-partition is under /. Since the command recursively changes the type of all mounts, this should do the trick. Could be the last command before starting k3s...

right, what I'm concerned here is try to break user-contract, and allow to have that set as soon as possible to avoid any possible race - and user assumption when it can be expected those to be set. I'd prefer to have those as early as possible (as soon as a fs is set up) but that seems to be tricky. I'll first try to get a baseline and we can revisit this later on.

**Comment by christianprim** [comment]
> right, what I'm trying to be careful here is to not break user-contract, and allow to have that set as soon as possible to avoid any possible race - and user assumption when it can be expected those to be effectively ready in the system. I'd prefer to have those as early as possible (as soon as a fs is set up) but that seems to be tricky. I'll first try to get a baseline and we can revisit this later on.

Good point!

**Comment by christianprim** [comment]
Just for your information: mounts are shared when the command is executed in the network stage (did this for testing purposes in  /oem/90_custom.yaml). But this may be very late in the boot process... [partition 2, 4 and 5 are remounted rather late in the boot-process, especially partition 4]
